<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnsubmit</name>
   <tag></tag>
   <elementGuidId>2376681d-fadd-4bc7-8ca8-c9a4424ca483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/div[3]/div[2]/div/div/div[2]/div[3]/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnsubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef27fe32-ec61-4ef5-b32c-0ec6e94d72f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c3ab1d3a-b099-45ad-bd11-e0e31f9d1885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnsubmit</value>
      <webElementGuid>f95f5bef-cc08-4b73-8b76-2c56a676c917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>0848b809-3ec4-4ca9-9f40-44aec63ab2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnsubmit</value>
      <webElementGuid>c307605f-6c14-4bd2-9741-3e344996e05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-md</value>
      <webElementGuid>ecb8e9f2-7ef7-40a0-85da-9c8d992f54e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnsubmit&quot;)</value>
      <webElementGuid>5f69e90c-7a92-48a3-b1a2-3e8f9abc2558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnsubmit']</value>
      <webElementGuid>9488b30d-0331-410f-aca7-2c112aebe828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/div/div/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>a26c6000-e2eb-4922-b17d-4e8fd727734b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>05179c6c-031c-4148-bb1d-dcdf9d99d12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnsubmit' and @id = 'btnsubmit']</value>
      <webElementGuid>7a53c280-d295-443d-899d-bb0ab3ecd2e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
