<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_I forgot my password_col-4</name>
   <tag></tag>
   <elementGuidId>fb31c882-14a7-473a-b7b2-0907050a68ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/div[3]/div[2]/div/div/div[2]/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5fd3d18c-4b49-4fc1-8276-495e1bc16d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-4</value>
      <webElementGuid>069a021a-69f3-4ba7-a52b-7382a97f0a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;login-box&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body login-card-body m-0 p-0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-5 bg-orange&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-4&quot;]</value>
      <webElementGuid>d9c74b5e-c5e7-4b7c-b7f4-a9a60e6ab52c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/div/div/div[2]/div[3]/div[2]</value>
      <webElementGuid>e73832b0-4f9d-4865-be69-3d970bd10c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I forgot my password'])[1]/following::div[1]</value>
      <webElementGuid>b324f4f1-0a6f-428c-9331-84738f2d9e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@2021 Mysystem'])[1]/preceding::div[1]</value>
      <webElementGuid>bd060817-872d-4807-802d-49c9e64a4be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]</value>
      <webElementGuid>7ac05117-8fb9-4730-acad-dad91f76b8bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
