<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expand</name>
   <tag></tag>
   <elementGuidId>88d90ab0-31a8-45e1-aa2e-6df68f4ddfd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='TreeView1n5']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8d115ed7-038f-4500-9408-f47614800cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/NewMysystemFirda/WebResource.axd?d=V4jZQ5INloX8_sbez5sDtELqZ8--Q9uymMEB303Z_p3DLVjF_ICKnDluNG0H__uGIpfBQLP2_7JbYywZMwHc_rrNko-azJsvvD4-dlxBseg1&amp;t=637823617705833095</value>
      <webElementGuid>b5c452c9-e90b-4219-88d2-d5a43b8e39e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Expand </value>
      <webElementGuid>05988ff6-a111-42bf-8b9f-4b996de1f2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1n5&quot;)/img[1]</value>
      <webElementGuid>adbfb704-1dc5-4ccc-859b-1ed080500939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='TreeView1n5']/img</value>
      <webElementGuid>4d62426e-afa7-41e0-b908-70f450522d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Expand ']</value>
      <webElementGuid>3905b3b7-1bae-4491-aa94-377ababda2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td/a/img</value>
      <webElementGuid>61ecfb90-67a2-43a9-9218-afea0ecdcc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/NewMysystemFirda/WebResource.axd?d=V4jZQ5INloX8_sbez5sDtELqZ8--Q9uymMEB303Z_p3DLVjF_ICKnDluNG0H__uGIpfBQLP2_7JbYywZMwHc_rrNko-azJsvvD4-dlxBseg1&amp;t=637823617705833095' and @alt = 'Expand ']</value>
      <webElementGuid>0b9d6944-198b-4614-886c-147ed5d8f706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
