<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KTP Pemilik</name>
   <tag></tag>
   <elementGuidId>c0dd92ed-101e-47f0-b4a6-05f92b75b712</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvLegalitas_FileUpload1_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_gvLegalitas_FileUpload1_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb8b15d2-06b3-4b44-a6c6-6d35ecc66ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>f7c68c6d-c909-4ee9-b074-1b676ab1d7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvLegalitas$ctl03$FileUpload1</value>
      <webElementGuid>39f04b5f-cd01-4808-802f-eac7240af938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvLegalitas_FileUpload1_1</value>
      <webElementGuid>7660737c-4bfa-4e2d-907b-58d6eb289c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>88623ed2-5e00-4ab6-941c-573b147b133e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvLegalitas_FileUpload1_1&quot;)</value>
      <webElementGuid>9eb8816a-a51c-4dde-bc83-0708069726ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvLegalitas_FileUpload1_1']</value>
      <webElementGuid>ea1c0e23-3644-4cbd-a345-2fc2e1c4af12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvLegalitas']/tbody/tr[3]/td[5]/input</value>
      <webElementGuid>06d84a05-0fc1-42b2-a748-b2bf73c7d244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/input</value>
      <webElementGuid>cd2f446a-a491-4a26-bc81-3c54296d643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'ctl00$main$gvLegalitas$ctl03$FileUpload1' and @id = 'main_gvLegalitas_FileUpload1_1']</value>
      <webElementGuid>d2e955e5-ca2a-4b70-9f2d-948f98ce16d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
