<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SIUP</name>
   <tag></tag>
   <elementGuidId>2013c989-495d-4507-a565-9cc4cf32fb70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvLegalitas_FileUpload1_5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_gvLegalitas_FileUpload1_5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2a3fedd-1423-4100-981b-8d329f7238f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>cd0ff491-f357-4e4c-80ea-fbacca0ddd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvLegalitas$ctl07$FileUpload1</value>
      <webElementGuid>9f26ba8a-e484-4a1b-9f5b-388ab6f75a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvLegalitas_FileUpload1_5</value>
      <webElementGuid>2cbf96d1-ec3e-422d-b570-581e68ffc826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a9e43d1c-b7f3-4af9-81e6-80bd9273159b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvLegalitas_FileUpload1_5&quot;)</value>
      <webElementGuid>ea0fb5cb-6209-419d-bd1a-1648df14ffb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvLegalitas_FileUpload1_5']</value>
      <webElementGuid>225edd0a-c3cb-486b-8777-c38579298338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvLegalitas']/tbody/tr[7]/td[5]/input</value>
      <webElementGuid>8e64c899-067e-4307-bf37-a911768e1525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[5]/input</value>
      <webElementGuid>41477dd4-42b8-45b6-8194-210850f4f0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'ctl00$main$gvLegalitas$ctl07$FileUpload1' and @id = 'main_gvLegalitas_FileUpload1_5']</value>
      <webElementGuid>4b3d749f-f4c8-49f1-9f8f-d3828f9dd1ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
