<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Foto</name>
   <tag></tag>
   <elementGuidId>7c7522c4-80a1-45ff-a570-b8f526871233</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvLegalitas_FileUpload1_7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_gvLegalitas_FileUpload1_7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5b4a43a-e421-49c8-9b4e-fe75927113ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>efd1a41d-7321-4e1f-bfc8-a8e5befb025d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvLegalitas$ctl09$FileUpload1</value>
      <webElementGuid>c9d97a71-406a-4899-b962-5ff793a64ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvLegalitas_FileUpload1_7</value>
      <webElementGuid>30c55417-18bb-4387-8931-20ecefcb30ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a28aa275-a670-42a1-b6c8-0a6bf08e2d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvLegalitas_FileUpload1_7&quot;)</value>
      <webElementGuid>4edd2f02-7e45-436f-98eb-f4b673927f95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvLegalitas_FileUpload1_7']</value>
      <webElementGuid>d60db5d5-92d5-4a86-a69a-98f5c69f0e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvLegalitas']/tbody/tr[9]/td[5]/input</value>
      <webElementGuid>1274e816-5479-4757-8421-94c7366ced57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[5]/input</value>
      <webElementGuid>9ef38f60-c7b0-4e6b-81ea-a4256ea5c3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'ctl00$main$gvLegalitas$ctl09$FileUpload1' and @id = 'main_gvLegalitas_FileUpload1_7']</value>
      <webElementGuid>3efe1f96-bfa6-4922-9d70-4b21c09f8627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
