<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SertifikasiProfesi</name>
   <tag></tag>
   <elementGuidId>604ea14d-7d14-4850-b0b6-8b65f33b1674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvLegalitas_FileUpload1_8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_gvLegalitas_FileUpload1_8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d611ee97-44b6-42a4-8346-1071fbece4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>959a04de-1910-4a77-8d78-376be8655a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvLegalitas$ctl10$FileUpload1</value>
      <webElementGuid>033e01b5-e4c1-4452-baf0-9432ab515165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvLegalitas_FileUpload1_8</value>
      <webElementGuid>fd398902-1328-4bfc-a259-ea4e854dd361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9165fa0c-71c7-4763-aa7e-d7dd3e81564f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvLegalitas_FileUpload1_8&quot;)</value>
      <webElementGuid>0e921446-27bc-4ccd-8161-eed4e9593a44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvLegalitas_FileUpload1_8']</value>
      <webElementGuid>5d6d63a1-5953-49f0-b50f-352206645312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvLegalitas']/tbody/tr[10]/td[5]/input</value>
      <webElementGuid>c72bfc5d-202d-4c2f-b26c-95e6fcd6f136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[5]/input</value>
      <webElementGuid>cfd01d12-d397-4aef-8da5-9b9dd1e641ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'ctl00$main$gvLegalitas$ctl10$FileUpload1' and @id = 'main_gvLegalitas_FileUpload1_8']</value>
      <webElementGuid>e645ca0a-f7bd-49a0-8212-70ff165f7a22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
