<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AktaPendirian1</name>
   <tag></tag>
   <elementGuidId>d5aeaa3a-4f5c-4dbf-a08f-f489fced5ade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='main_gvLegalitas_FileUpload1_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main_gvLegalitas_FileUpload1_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8108d35-162b-4530-8fb2-c593b02405e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>d7058788-a696-45d0-9fce-abd4f3bf7666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$main$gvLegalitas$ctl04$FileUpload1</value>
      <webElementGuid>2a4d1327-45ea-4c74-871d-8b003164f9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_gvLegalitas_FileUpload1_2</value>
      <webElementGuid>da2d6dec-ba5d-4a37-950c-632d1d3df118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f4023e51-0725-4381-b2a4-59cd82618573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_gvLegalitas_FileUpload1_2&quot;)</value>
      <webElementGuid>d66712d9-871f-49ee-b6da-2e5ddd4c34da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='main_gvLegalitas_FileUpload1_2']</value>
      <webElementGuid>89984c33-69b6-4870-927a-c9b552eb7b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='main_gvLegalitas']/tbody/tr[4]/td[5]/input</value>
      <webElementGuid>aefa331f-355e-47fa-99ae-f7072c440670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/input</value>
      <webElementGuid>95ad4b67-3e09-4dbf-8a48-8cb9ce085ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'ctl00$main$gvLegalitas$ctl04$FileUpload1' and @id = 'main_gvLegalitas_FileUpload1_2']</value>
      <webElementGuid>e4ad4f27-58a9-45eb-8a61-a40615486dea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
