<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MasterVendor</name>
   <tag></tag>
   <elementGuidId>2868436e-71a9-476c-a074-955d1e83dd53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TreeView1n5Nodes']/table/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.TreeView1_2.TreeView1_8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6d174be1-519a-4165-87be-f1ce53af8d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TreeView1_2 TreeView1_8</value>
      <webElementGuid>16c7ac1d-7bfd-4e8e-839f-9c84b450fbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>TreeView_HoverNode(TreeView1_Data, this)</value>
      <webElementGuid>92844fb9-fa40-4ebe-8beb-df9c85eb0206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>TreeView_UnhoverNode(this)</value>
      <webElementGuid>7e4938dc-8af9-4095-a953-225d4a7a4980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master Vendor</value>
      <webElementGuid>9b18d85e-a1d6-43e2-8893-6019dca4cacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TreeView1n5Nodes&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;TreeView1_2 TreeView1_8&quot;]</value>
      <webElementGuid>71d47651-c505-4ff8-88ff-d48928ef4b9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TreeView1n5Nodes']/table/tbody/tr/td[3]</value>
      <webElementGuid>b2da574e-cc61-4e4e-86be-14a31a4da111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor'])[1]/following::td[3]</value>
      <webElementGuid>a1eaeb9d-ba68-464f-9000-e8c570010aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Jenis Barang'])[1]/following::td[5]</value>
      <webElementGuid>054e047c-4878-4e62-a542-9c5fe90dd4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review &amp; Verifikasi'])[1]/preceding::td[3]</value>
      <webElementGuid>1c8c1a4c-d800-4bb5-bfa5-246d196d2d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[3]</value>
      <webElementGuid>20bc06d6-4812-4f30-b081-b3050c129754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Master Vendor' or . = 'Master Vendor')]</value>
      <webElementGuid>20956a5c-51a0-43dd-a538-26baaedfdd4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
