<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_treeContainer</name>
   <tag></tag>
   <elementGuidId>59338b2c-0f44-40ce-a207-b1d14edb9449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#treeContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='treeContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ba64de8a-b137-43c6-b9a0-43e4dab2ae77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>NewTree.aspx</value>
      <webElementGuid>1883e953-dac5-4ddb-b054-14e14c112126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeContainer</value>
      <webElementGuid>ca77cd12-989a-45a2-8533-8c2763234fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>baecbb79-f703-4964-8bad-2934415c60aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeContainer&quot;)</value>
      <webElementGuid>8e140151-60e7-4130-92d8-c662348e76a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='treeContainer']</value>
      <webElementGuid>ed9099a7-aafc-4d06-990f-e1511a2b02d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/iframe[2]</value>
      <webElementGuid>5d6e38b6-94bb-4a22-b6af-ffa2971502be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[2]</value>
      <webElementGuid>922041c0-9bcd-4d04-9385-59a0ec3af7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'NewTree.aspx' and @id = 'treeContainer']</value>
      <webElementGuid>f6024413-e7f9-475b-94fe-c1c19e91c53d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
