<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Img_menu</name>
   <tag></tag>
   <elementGuidId>215eda6c-dbdf-493c-b090-dc9e763a71c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgMenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgMenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8e94a0b8-41b3-4860-8a74-475097e72bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgMenu</value>
      <webElementGuid>796a2262-3d38-4828-9078-d3b56a1e1203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Images/menu.png</value>
      <webElementGuid>53ae2db6-90e1-4a44-b7ac-0ed3f57a32a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgMenu&quot;)</value>
      <webElementGuid>24954393-be21-4f2d-a40e-264294e53443</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgMenu']</value>
      <webElementGuid>13e576a7-b556-474f-a4fc-19766129425b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMenuPadding']/img</value>
      <webElementGuid>81a38d21-12ca-4712-a1e6-e943de9a8601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>7910007c-c41d-45c1-acae-ed12121be73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgMenu' and @src = 'Images/menu.png']</value>
      <webElementGuid>061434e5-9f66-4e73-b721-20352e49742f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
