<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_select</name>
   <tag></tag>
   <elementGuidId>eadef74a-8176-41df-88ae-c3ed4c7cc782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>35130729-636e-4dd3-951c-fbcaf9634c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>61af44fb-9112-48af-a395-9d6039dd8060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:ProductOfferingLookup('ucLookupProdOffer_uclProductOffering_txt','ucLookupProdOffer_uclProductOffering_hd1','MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL ','ucLookupProdOffer_uclProductOffering_hd2','27843','ucLookupProdOffer_uclProductOffering_hd3','MGIPMOPIN');;overlay('mdnucLookupProdOffer_uclProductOffering');__doPostBack('mdnucLookupProdOffer_uclProductOffering', '')</value>
      <webElementGuid>856eff28-59fa-4a25-b2c6-a0b6cf1bf3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>9e9c25d7-e0ba-4ca6-ab82-e7932ef1a390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>fba84180-789f-4a9f-b9ff-b8390741d424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New App Motorcycle/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>c45f5c46-4c52-411c-bbbf-41c8a9dc97ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>450a6231-9605-4d63-b84b-6aa5092c6c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL']/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>12a9c24f-06ac-492e-a535-eea000019732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>8b46e7cd-6e30-4e74-83a0-2436f8c3fccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MGIPMOPIN'])[1]/following::a[1]</value>
      <webElementGuid>d2780f23-a5ec-4438-ba16-6a0378c9745c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL'])[1]/following::a[1]</value>
      <webElementGuid>c93a42a0-7e95-4ef7-8737-df8830b5a682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PEMBIAYAAN MULTIGUNA INSTALLMENT PAYMENT 2W NEW BIKE - REGULER'])[1]/preceding::a[1]</value>
      <webElementGuid>6277a103-faa1-40ae-96fc-2fe4dd140d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MGIPNB0000'])[1]/preceding::a[1]</value>
      <webElementGuid>dab62c4a-58cb-42f4-8a99-574cc11c2259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>3905d49c-ff45-44bc-a57d-95b3f00b64bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:ProductOfferingLookup('ucLookupProdOffer_uclProductOffering_txt','ucLookupProdOffer_uclProductOffering_hd1','MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL ','ucLookupProdOffer_uclProductOffering_hd2','27843','ucLookupProdOffer_uclProductOffering_hd3','MGIPMOPIN');;overlay('mdnucLookupProdOffer_uclProductOffering');__doPostBack('mdnucLookupProdOffer_uclProductOffering', '')&quot;)]</value>
      <webElementGuid>b57e0d02-2fe8-4695-b060-5c9bf1acbfa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>ccf62787-e65f-48e9-9b33-8bf86cbc733e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucLookupProdOffer_uclProductOffering_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:ProductOfferingLookup(&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;MUTIGUNA INSTALLMENT PAYMENT MOP - INTERNAL &quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;27843&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucLookupProdOffer_uclProductOffering_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;MGIPMOPIN&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucLookupProdOffer_uclProductOffering&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucLookupProdOffer_uclProductOffering&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>18efa021-2896-4dc2-8438-e88ae766f95c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
