<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_NewAppMotorcycle</name>
   <tag></tag>
   <elementGuidId>353ba094-3c5e-44d6-b74a-871f7768ffe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.rtIn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='return false']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c0df6955-0848-4294-92f6-35aad6eb03ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rtIn</value>
      <webElementGuid>f2236c8f-461a-4a35-a0c8-b811a4d71a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>cd97a89a-353d-47fa-ad8b-56c7dd55a66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>LOS.X/CREDITPROCESS/NEWAPPLICATION/APPLICATIONX.ASPX?BLCODE=CFMCY</value>
      <webElementGuid>499888d0-f52d-404a-966a-59dd677d03fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New App Motorcycle</value>
      <webElementGuid>43fa7aed-1f54-4316-89ec-f8545d24c540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rtvMenuTree&quot;)/ul[@class=&quot;rtUL rtLines&quot;]/li[@class=&quot;rtLI rtFirst&quot;]/div[@class=&quot;rtTop  rtSelected rtHover&quot;]/a[@class=&quot;rtIn&quot;]</value>
      <webElementGuid>4a120af5-ba6a-402d-b362-829d51f8c354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/New App Motorcycle/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_treeContainer</value>
      <webElementGuid>3aa690f9-f84a-435b-a5af-886ad693c661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='return false']</value>
      <webElementGuid>096131c0-2317-48c8-a061-7706b9d72a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rtvMenuTree']/ul/li/div/a</value>
      <webElementGuid>39008b7b-dbae-45b7-8020-6a6212475c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New App Motorcycle')]</value>
      <webElementGuid>1b2eec97-8da1-4804-b050-b927006babf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Process'])[1]/following::a[1]</value>
      <webElementGuid>5c43d003-2198-42da-8086-75c54f76c2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Favourite'])[1]/following::a[1]</value>
      <webElementGuid>c2c0eaaa-0493-40d9-a2d6-603b5b5b4d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New App Car'])[1]/preceding::a[1]</value>
      <webElementGuid>051ba646-b8f6-4f5d-8e41-967732eedee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New App Multiguna Jasa'])[1]/preceding::a[2]</value>
      <webElementGuid>767b3ccd-f3e7-4712-abbc-1dacf04ee6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New App Motorcycle']/parent::*</value>
      <webElementGuid>8f5b7e5f-5a05-454b-a086-054b0c2a4d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'LOS.X/CREDITPROCESS/NEWAPPLICATION/APPLICATIONX.ASPX?BLCODE=CFMCY')]</value>
      <webElementGuid>1a848e8e-eefb-4948-bdd3-e583bec290c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>7fc70cb7-09d9-49ce-900e-524ef67591fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'LOS.X/CREDITPROCESS/NEWAPPLICATION/APPLICATIONX.ASPX?BLCODE=CFMCY' and (text() = 'New App Motorcycle' or . = 'New App Motorcycle')]</value>
      <webElementGuid>6c61b84a-6cba-4f78-a137-7dad3022bcf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
