<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_savecontinue</name>
   <tag></tag>
   <elementGuidId>09e59cd3-3272-4ec2-bbef-4b4dd61db4f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lb_Form_SaveCont</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lb_Form_SaveCont']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0aa88e07-1b70-4cb5-8955-8cd6938b8109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bbd5b5a1-bf57-412f-9a4c-66a435b6a86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lb_Form_SaveCont</value>
      <webElementGuid>e4aa6b37-b12d-479c-bfdd-678ab2fcc67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save &amp; Continue</value>
      <webElementGuid>90da0238-3342-4ec6-8b69-99fdc42faf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;lb_Form_SaveCont&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>cd9eb130-8895-4fca-9619-6223303e802e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lb_Form_SaveCont</value>
      <webElementGuid>6d7f1de1-74d5-4173-a6d9-f7b5e8d639c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>67d82d09-b36e-44ce-a981-5a68c6deb4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lb_Form_SaveCont&quot;)</value>
      <webElementGuid>d3ee3307-bc61-4c39-bdc7-c0acd8b1570a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_ApplicationData/iframe_Term  Condition_appForm</value>
      <webElementGuid>7ccd04cf-952c-4953-9a94-6305605d560b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lb_Form_SaveCont']</value>
      <webElementGuid>09050988-b0c1-481d-a832-981cd3a40391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upSaveCancel']/table/tbody/tr/td/div/input</value>
      <webElementGuid>4ef30c6c-f653-49a3-8717-650f7cd7043d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/input</value>
      <webElementGuid>3a501bbe-3b35-4967-af6f-bd35250aa4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'lb_Form_SaveCont' and @id = 'lb_Form_SaveCont']</value>
      <webElementGuid>3c950e08-17b8-4aac-b983-8e4327eb676e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
