<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_search</name>
   <tag></tag>
   <elementGuidId>5798a9cc-e95b-4e56-a482-c6f9631c8ae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_ucS_lbSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_ucS_lbSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6adbfdf4-f0a3-44e3-a720-715c19e92325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_ucS_lbSearch</value>
      <webElementGuid>ab1810b3-550e-4d58-a4f1-a6c8f13b1c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnForm</value>
      <webElementGuid>1afc023c-d699-4fc4-aef6-0fbfe6ce378e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucAddr$ucLookupZipCode$uclZipCode$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))</value>
      <webElementGuid>6f25da51-3e39-4126-ab16-5a89cf179a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>b9a332c2-4f26-4e7d-8d1f-07a979ed561a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_ucS_lbSearch&quot;)</value>
      <webElementGuid>27cbb4a3-b896-4243-8f38-bf429ca9adfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_ApplicationData/iframe_Term  Condition_appForm</value>
      <webElementGuid>b3eb595c-84d0-4f05-b91b-fede144decb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_ucS_lbSearch']</value>
      <webElementGuid>66ab60d5-d207-49bc-aa3e-4888bca6c7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_ucS_upButtonSearch']/a</value>
      <webElementGuid>0dae0881-ceb0-4d5d-b1c9-b9afeadfc444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SEARCH')]</value>
      <webElementGuid>ded1c91d-9701-4981-bb27-17de2fb65262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code'])[2]/following::a[1]</value>
      <webElementGuid>a3cf9b94-2809-4968-833a-1d6bf2daacb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::a[1]</value>
      <webElementGuid>8bff2cb5-8423-4fb9-8c9e-dbd2f4237cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[1]/preceding::a[1]</value>
      <webElementGuid>2413d72f-7608-4fff-91ab-a19ea521351b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan'])[2]/preceding::a[2]</value>
      <webElementGuid>dbaf37f2-1d90-4b13-9d3d-c711a88f588b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>d177dea6-b026-4cf5-8454-d83061f1fccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucAddr$ucLookupZipCode$uclZipCode$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))')]</value>
      <webElementGuid>3f9a1417-653f-4a38-8fb7-565a0cd0ef72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a</value>
      <webElementGuid>076c2639-6342-4a39-b856-e336bbbb1ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_ucS_lbSearch' and @href = 'javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ucAddr$ucLookupZipCode$uclZipCode$umd$ctl00$ucS$lbSearch&quot;, &quot;&quot;, true, &quot;ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_ucS_lbSearchVldtnGrp&quot;, &quot;&quot;, false, true))' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>7360f280-91bb-4842-b0e5-d9020615035f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
