<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</name>
   <tag></tag>
   <elementGuidId>472013a5-2266-4bc9-b284-346c2a415047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainPage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainPage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>48778165-d044-42ba-9b15-abf0073777b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainPage</value>
      <webElementGuid>8e44ee35-6bc6-4f68-a150-3ffda66bdd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mainPage</value>
      <webElementGuid>b2edd946-8dd8-4380-a515-5a93cbbd3ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab2ded3c-fda3-4baf-9dd8-390c5f409cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>LOS.X/CREDITPROCESS/NEWAPPLICATION/APPLICATIONX.ASPX?BLCODE=CFMCY</value>
      <webElementGuid>5c963d29-8966-4dcd-9704-40e5981cb124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainPage&quot;)</value>
      <webElementGuid>09e91176-2cfa-47c4-b652-ccc8d0e238eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainPage']</value>
      <webElementGuid>efabc727-9250-4d5f-b245-043c3857d137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/iframe[3]</value>
      <webElementGuid>16ae8ab8-8f7b-41a3-8f61-953b98d231a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[3]</value>
      <webElementGuid>9729b68b-c4c4-4d2c-b383-45d15d14fa8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mainPage' and @name = 'mainPage' and @src = 'LOS.X/CREDITPROCESS/NEWAPPLICATION/APPLICATIONX.ASPX?BLCODE=CFMCY']</value>
      <webElementGuid>08917537-875b-496a-86d1-4bd61456514e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
