<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_tenor</name>
   <tag></tag>
   <elementGuidId>43bb5485-8739-4ec3-9ccc-6fa68ba6516e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucINTenor_txtInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucINTenor_txtInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b350bef9-5499-4e9d-9ddf-890cdafe6337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucINTenor$txtInput</value>
      <webElementGuid>0a1188e6-ae79-4cbb-9347-d277a2f909f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98216526-83b5-44a8-a056-984a75c19877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f3842033-dc25-48e6-ac49-4c518ca4070f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ucINTenor$txtInput\',\'\')', 0)</value>
      <webElementGuid>13197b8d-821f-4dbe-be48-5f7981e76490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (WebForm_TextBoxKeyHandler(event) == false) return false;return validateKey(event);</value>
      <webElementGuid>3dda50e9-b66e-447b-8ad8-ad255de6b26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucINTenor_txtInput</value>
      <webElementGuid>8356fa7b-d929-4d24-ab86-a4bb61569eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtMedPercentageStyle</value>
      <webElementGuid>a892f473-d396-4c45-a7d9-87612352b068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return (event.keyCode!=13);</value>
      <webElementGuid>986c89e0-cafd-4469-9442-70381aa563fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>formatValueInteger('ucINTenor_txtInput','ucINTenor_hdnInput','ucINTenor_txtInputDummy');</value>
      <webElementGuid>3c5d63c4-7ffb-49d5-a7ac-d2e93acbb0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearFormatValue('ucINTenor_txtInput');</value>
      <webElementGuid>247a8f45-0e7d-4c08-8f24-ab508928155d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucINTenor_txtInput&quot;)</value>
      <webElementGuid>137f31df-cca1-474a-8402-04abd6267997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_ApplicationData/iframe_Term  Condition_appForm</value>
      <webElementGuid>e6403844-08a7-4f82-8fe7-50e7e71d48dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucINTenor_txtInput']</value>
      <webElementGuid>7877229d-4484-4c16-90f5-fa0fd68dccb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dAppData']/table/tbody/tr[2]/td[2]/input[2]</value>
      <webElementGuid>9f240784-9e9d-4791-9dad-476e514b49d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>1004657b-fc5c-401a-8dbd-496d6567dfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucINTenor$txtInput' and @type = 'text' and @id = 'ucINTenor_txtInput']</value>
      <webElementGuid>c7e923b2-beef-44bd-a328-8e50eef15f98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
