<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_appno</name>
   <tag></tag>
   <elementGuidId>8ba26cdc-2de8-4a04-a7db-752c17aca34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtProspectNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtProspectNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7c03b89-fe69-41d9-8e0b-21a3e06bea3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtProspectNo</value>
      <webElementGuid>fc165672-9d8c-4698-890c-555d339d708d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8395ac7f-6804-447c-a89d-55976fdafa32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1879a871-001f-4d77-a35a-703931f1f563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtProspectNo</value>
      <webElementGuid>90ba4ced-4f33-4dfc-b1fb-d1c465d74f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtProspectNo&quot;)</value>
      <webElementGuid>82e8254d-4307-4792-be65-56f06dea8141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_ApplicationData/iframe_Term  Condition_appForm</value>
      <webElementGuid>50edc702-f042-4698-a7f3-5bc547b4053e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtProspectNo']</value>
      <webElementGuid>60339e79-20b5-48d0-a151-ba369a7378b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trProspectNo']/td[2]/input</value>
      <webElementGuid>73891314-122c-4b95-bbbf-dc4727edbde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>f9b178d3-e37a-4977-94a5-bab9e20de518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtProspectNo' and @type = 'text' and @id = 'txtProspectNo']</value>
      <webElementGuid>a621e760-549b-4760-9ff3-acca9b90cd03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
