<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_rt</name>
   <tag></tag>
   <elementGuidId>9447c2d8-ccc5-4f13-8630-e8f8a45ba03a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucAddr_txtRT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucAddr_txtRT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1c1eea6-f22a-48bd-8909-7c3b9fdbfdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucAddr$txtRT</value>
      <webElementGuid>2bcc8597-642c-402e-88c8-290e192dd7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20a4b4e7-7841-45d0-bf45-772d9ea3558c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7778bef3-ab5c-4a14-8591-fa969cfd2b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAddr_txtRT</value>
      <webElementGuid>68c930cd-e17a-48af-933f-6f2699c26596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtShortInputStyle</value>
      <webElementGuid>ff63020b-9698-478e-8739-3d01cd021227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucAddr_txtRT&quot;)</value>
      <webElementGuid>2170400f-4c29-448c-b4d8-b437020d6d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_ApplicationData/iframe_Term  Condition_appForm</value>
      <webElementGuid>598c7a85-c17e-4a5f-9829-4fbee2b0331f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucAddr_txtRT']</value>
      <webElementGuid>0c5db215-1945-413b-ba52-91cbdbec62c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucAddr_divAddress']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>13f9577d-f5c7-4dc7-a349-7ceaba40ad64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>56ab6bdd-9cc2-4ffe-a39d-c8108c3912f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucAddr$txtRT' and @type = 'text' and @id = 'ucAddr_txtRT']</value>
      <webElementGuid>140cf75e-9365-42d0-8fd5-d4133dd46ccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
