<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_zipcode</name>
   <tag></tag>
   <elementGuidId>1f44fe89-b27e-40be-ac25-e4187b5560dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucAddr_ucLookupZipCode_uclZipCode_imb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucAddr_ucLookupZipCode_uclZipCode_imb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b292799a-ade4-48c4-8eb3-bf63d7c05e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>a5d16ab4-2d90-4098-931e-f9ee144d50d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucAddr$ucLookupZipCode$uclZipCode$imb</value>
      <webElementGuid>31a225ed-cfbd-4343-b3c5-dfce9c6bbeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAddr_ucLookupZipCode_uclZipCode_imb</value>
      <webElementGuid>0e67ff05-42c8-4ab4-b932-2a6b978a728c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>cbafd4c9-587a-4700-b501-ad52d5ce6949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnucAddr_ucLookupZipCode_uclZipCode');</value>
      <webElementGuid>13a07695-438d-4feb-8f8b-b0fd13eec43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucAddr_ucLookupZipCode_uclZipCode_imb&quot;)</value>
      <webElementGuid>7a231b0e-da99-4df9-8224-bb8151bcd999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_ApplicationData/iframe_Term  Condition_appForm</value>
      <webElementGuid>d5a36544-ba3a-4d75-ac7b-185535b52aa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucAddr_ucLookupZipCode_uclZipCode_imb']</value>
      <webElementGuid>8d786fc3-5c48-4e85-8d62-cc5c5029bebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ucAddr_divAddress']/table/tbody/tr[3]/td[2]/ul/li/input[2]</value>
      <webElementGuid>bcf37ba5-7492-4e92-821b-c9278072908c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input[2]</value>
      <webElementGuid>1c76a502-d571-488b-89db-e2ad9e1d2146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ucAddr$ucLookupZipCode$uclZipCode$imb' and @id = 'ucAddr_ucLookupZipCode_uclZipCode_imb' and @src = '../../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>203b0269-e222-4070-8713-963eb64e8f70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
