<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_zipcode</name>
   <tag></tag>
   <elementGuidId>40f7d351-97fb-46f4-aa05-1aa75c612487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7505c4b-c33c-4988-a463-16183715e0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>67bed6ba-7ae2-46f6-b091-8ba0a1f12be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:ZipCode('ucAddr_ucLookupZipCode_uclZipCode_txt','ucAddr_ucLookupZipCode_uclZipCode_hd1','16421','ucAddr_ucLookupZipCode_uclZipCode_hd2','BEJI','ucAddr_ucLookupZipCode_uclZipCode_hd3','BEJI','ucAddr_ucLookupZipCode_uclZipCode_hd4','DEPOK','ucAddr_ucLookupZipCode_uclZipCode_hd5','','ucAddr_ucLookupZipCode_uclZipCode_hd6','1642100','ucAddr_ucLookupZipCode_uclZipCode_hd7','Depok, Kota.','ucAddr_ucLookupZipCode_uclZipCode_hd8','9376');;overlay('mdnucAddr_ucLookupZipCode_uclZipCode');__doPostBack('mdnucAddr_ucLookupZipCode_uclZipCode', '')</value>
      <webElementGuid>facddfdd-6835-49c8-8903-239ba0f4cdeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>a7ede659-0ce3-447f-89e4-ec108e77653a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>7669bb8a-e1bb-4e58-94a4-b8ae28f2ce7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_ApplicationData/iframe_Term  Condition_appForm</value>
      <webElementGuid>2aa80f35-04c5-48c6-b9c9-951428a77c14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>79539f76-fc7b-4a90-8963-4233a03b4813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_gvL']/tbody/tr[2]/td[8]/a</value>
      <webElementGuid>f25cbb1a-e231-48e0-a8ab-c9c5695aaa09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>d9ff5ce6-cf1b-486b-9ab3-33fdba08a4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depok, Kota.'])[1]/following::a[1]</value>
      <webElementGuid>595020b6-cc75-4e2b-b466-23f085d7ae5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEPOK'])[1]/following::a[1]</value>
      <webElementGuid>8289810e-b5aa-43f6-945a-ad9db4d52536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BEJI'])[3]/preceding::a[1]</value>
      <webElementGuid>3496df8d-4a09-452e-89a4-33b3002bef61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNGARAN TIMUR'])[1]/preceding::a[1]</value>
      <webElementGuid>2ea76280-42a8-4a35-b637-5d1bbbb0fdcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>5f84aa30-916f-49e1-bc0e-ed5ad633960e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:ZipCode('ucAddr_ucLookupZipCode_uclZipCode_txt','ucAddr_ucLookupZipCode_uclZipCode_hd1','16421','ucAddr_ucLookupZipCode_uclZipCode_hd2','BEJI','ucAddr_ucLookupZipCode_uclZipCode_hd3','BEJI','ucAddr_ucLookupZipCode_uclZipCode_hd4','DEPOK','ucAddr_ucLookupZipCode_uclZipCode_hd5','','ucAddr_ucLookupZipCode_uclZipCode_hd6','1642100','ucAddr_ucLookupZipCode_uclZipCode_hd7','Depok, Kota.','ucAddr_ucLookupZipCode_uclZipCode_hd8','9376');;overlay('mdnucAddr_ucLookupZipCode_uclZipCode');__doPostBack('mdnucAddr_ucLookupZipCode_uclZipCode', '')&quot;)]</value>
      <webElementGuid>71877525-f3ca-4c47-9469-6a673559c05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a</value>
      <webElementGuid>0b018b0c-3dc2-4be4-824f-133e365207f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucAddr_ucLookupZipCode_uclZipCode_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:ZipCode(&quot; , &quot;'&quot; , &quot;ucAddr_ucLookupZipCode_uclZipCode_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucAddr_ucLookupZipCode_uclZipCode_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;16421&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucAddr_ucLookupZipCode_uclZipCode_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;BEJI&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucAddr_ucLookupZipCode_uclZipCode_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;BEJI&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucAddr_ucLookupZipCode_uclZipCode_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;DEPOK&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucAddr_ucLookupZipCode_uclZipCode_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucAddr_ucLookupZipCode_uclZipCode_hd6&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1642100&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucAddr_ucLookupZipCode_uclZipCode_hd7&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Depok, Kota.&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;ucAddr_ucLookupZipCode_uclZipCode_hd8&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;9376&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnucAddr_ucLookupZipCode_uclZipCode&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnucAddr_ucLookupZipCode_uclZipCode&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>9d17f649-60a5-425c-839d-04e0c7de066c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
