<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_appno</name>
   <tag></tag>
   <elementGuidId>ef6f37be-5c02-47e5-b0f0-0e766dd9656e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucCreditProcessMainInfo_lbAppNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ucCreditProcessMainInfo_lbAppNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>262b86d1-452b-47e1-917e-1f105bb01554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucCreditProcessMainInfo_lbAppNo</value>
      <webElementGuid>b3f8e56e-0ca7-49cd-972a-340f6eda22f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ucCreditProcessMainInfo$lbAppNo','')</value>
      <webElementGuid>5577f7d4-e6da-4612-a055-9c249cf1df8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>539APP20240200161</value>
      <webElementGuid>8caa25f4-51ad-4949-94b2-f8ccefed1c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucCreditProcessMainInfo_lbAppNo&quot;)</value>
      <webElementGuid>331130ff-e1cf-4ec1-b15c-cdaae00c7287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_ApplicationData/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>2e3a88de-578d-490d-9f00-1c369d4a6cd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ucCreditProcessMainInfo_lbAppNo']</value>
      <webElementGuid>403ab5a8-8049-49a2-979d-e443304c7cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dMainInfoUC']/table/tbody/tr/td[2]/a</value>
      <webElementGuid>bba6eb02-8bdd-487c-8334-8f951b9f2bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'539APP20240200161')]</value>
      <webElementGuid>b847f423-8c9f-4ab1-a063-07703860309f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Number'])[1]/following::a[1]</value>
      <webElementGuid>8143cc06-b3b7-4d62-a771-96ce026e8c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Info'])[1]/following::a[1]</value>
      <webElementGuid>b0d0e9e6-fa97-4f17-915d-951885a92a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Num Of Asset'])[1]/preceding::a[1]</value>
      <webElementGuid>1cb8dfb5-a2f6-4bef-8c9d-523e73dd2053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Original Office'])[1]/preceding::a[1]</value>
      <webElementGuid>212c75c2-c0c8-47fd-869e-3138a1db2239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='539APP20240200161']/parent::*</value>
      <webElementGuid>271a5f8d-4c29-4910-88d5-e0c8129ddbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ucCreditProcessMainInfo$lbAppNo','')&quot;)]</value>
      <webElementGuid>39046008-3610-42aa-99c8-8fed5beb5f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>a566955c-e11c-495d-a53d-2767bc4544b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ucCreditProcessMainInfo_lbAppNo' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ucCreditProcessMainInfo$lbAppNo&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '539APP20240200161' or . = '539APP20240200161')]</value>
      <webElementGuid>ec6a494b-e254-40c5-abba-26bfb4e00dcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
