<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_select</name>
   <tag></tag>
   <elementGuidId>9e89d1d5-70dc-4847-860a-d4df1581551d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1979a4b8-4ea3-4fc3-af45-91613bf551ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_umd_ctl00_gvL_hpSelect_0</value>
      <webElementGuid>1ae43c8c-b54f-4fcb-9c9e-3af38d1d674d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','HO HENDY','uclCust_uclCust_hd2','5010000304','uclCust_uclCust_hd3','P','uclCust_uclCust_hd4','Personal','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','TEST Rt.033 Rw.033 PONDOK CINA, BEJI, DEPOK, 16424','uclCust_uclCust_hd7','5830998','uclCust_uclCust_hd8','');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')</value>
      <webElementGuid>e8ab03a1-b721-4f7e-b902-f36164d5c1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>8678f9cb-bddd-41a6-bd9c-66968b03d71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclCust_uclCust_umd_ctl00_gvL_hpSelect_0&quot;)</value>
      <webElementGuid>b1079af7-510d-430e-b0c2-56f5be5e56aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>c0bd63bb-670b-4373-bc2b-3dfd4bbca3e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uclCust_uclCust_umd_ctl00_gvL_hpSelect_0']</value>
      <webElementGuid>0e7d549b-4498-492d-b86e-8af141a5ce90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='uclCust_uclCust_umd_ctl00_gvL']/tbody/tr[2]/td[6]/a</value>
      <webElementGuid>b5c42764-30e9-4517-be97-20e36e5947e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>23edfe69-a032-493f-9d8d-7eec67760dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEST Rt.033 Rw.033 PONDOK CINA, BEJI, DEPOK, 16424'])[1]/following::a[1]</value>
      <webElementGuid>b3f6093a-405d-4fc6-bdd2-b127f754ba9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::a[1]</value>
      <webElementGuid>1bcc1cad-e2e3-47a1-a1b5-565035203a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>707fa18b-71ee-463a-b148-f6bd4e82f23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>ead29cd7-2410-4349-926d-5c7ff5c0fbc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:CustLookup('uclCust_uclCust_txt','uclCust_uclCust_hd1','HO HENDY','uclCust_uclCust_hd2','5010000304','uclCust_uclCust_hd3','P','uclCust_uclCust_hd4','Personal','uclCust_uclCust_hd5','-','uclCust_uclCust_hd6','TEST Rt.033 Rw.033 PONDOK CINA, BEJI, DEPOK, 16424','uclCust_uclCust_hd7','5830998','uclCust_uclCust_hd8','');;overlay('mdnuclCust_uclCust');__doPostBack('mdnuclCust_uclCust', '')&quot;)]</value>
      <webElementGuid>677a56d6-8320-4816-b4b1-67b9efae3676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>b3a0a564-fda6-432a-afc7-f3d7a4475ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uclCust_uclCust_umd_ctl00_gvL_hpSelect_0' and @href = concat(&quot;javascript:CustLookup(&quot; , &quot;'&quot; , &quot;uclCust_uclCust_txt&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;HO HENDY&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd2&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;5010000304&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd3&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;P&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd4&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Personal&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd5&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd6&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;TEST Rt.033 Rw.033 PONDOK CINA, BEJI, DEPOK, 16424&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd7&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;5830998&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;uclCust_uclCust_hd8&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;);;overlay(&quot; , &quot;'&quot; , &quot;mdnuclCust_uclCust&quot; , &quot;'&quot; , &quot;);__doPostBack(&quot; , &quot;'&quot; , &quot;mdnuclCust_uclCust&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>7cb99323-6e0f-4a21-989b-5091d36a6ce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
