<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Term  Condition_appForm</name>
   <tag></tag>
   <elementGuidId>b7322bd2-b592-4091-9cce-1be3a0ce664a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='appForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>061bea9e-fc82-43e3-84a1-3ae653284cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/CustomerData/CustomerDataX.aspx?AppId=1631899&amp;AppSrc=</value>
      <webElementGuid>900dba0f-8947-4b36-aa2f-8b3ff8f0a207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appForm</value>
      <webElementGuid>51489815-66a4-4de2-81d3-1f87168b5bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appForm</value>
      <webElementGuid>9a7dd02f-7def-45cd-9e08-093b5f3e341b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bb067c40-579e-4783-beee-2857343f1b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appForm&quot;)</value>
      <webElementGuid>b36b45f8-92cc-4534-8cd9-97f14ece8d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_Customer/iframe_Welcome, Anita Gusti, KEDOYA, Credit Admin_mainPage</value>
      <webElementGuid>ff2d4b56-2c0b-444b-bd23-a3ef53abbdf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='appForm']</value>
      <webElementGuid>d78207d6-8c5a-4063-90d8-6329e41727dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appFormContainer']/iframe</value>
      <webElementGuid>e9166ccd-d93b-43c6-b769-d37dbcd66b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2e4052fd-ee13-49d4-8e5f-f3ebe04fec56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/CONFINS_TRAIN/LOS.X/CreditProcess/NewApplication/CustomerData/CustomerDataX.aspx?AppId=1631899&amp;AppSrc=' and @id = 'appForm' and @name = 'appForm']</value>
      <webElementGuid>6c38a135-f90f-49c7-ad5d-3aec44736473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
