<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_custname</name>
   <tag></tag>
   <elementGuidId>50264abd-04ca-431a-b89b-221830730a69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uclCust_uclCust_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8069988d-3685-4710-96a1-76f104a1cf48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uclCust$uclCust$umd$ctl00$ucS$rptFixedSearch$ctl01$txtSearchValue</value>
      <webElementGuid>66540f70-c4b1-4c11-b1d8-22c670c65a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed5cf946-3c88-4a51-9550-9bff83010e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0</value>
      <webElementGuid>749b766a-1a7d-4ce2-9e3b-465a99139e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txtInput</value>
      <webElementGuid>2843ca98-c28e-4488-8c60-1bf97e3dd2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclCust_uclCust_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0&quot;)</value>
      <webElementGuid>ea2b6f4e-36cd-4000-bdf5-f40e8abca4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>dfb90ae6-219d-4c5a-a95f-ad81796180ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uclCust_uclCust_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      <webElementGuid>1d405145-8722-4aeb-b875-2fa862b5fac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uclCust_uclCust_umd_ctl00_ucS_upFixedSearch']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>a9e697fb-1a39-48d1-8848-0a3e6c7de454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>005583d5-495b-464e-9130-576ea8d33e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'uclCust$uclCust$umd$ctl00$ucS$rptFixedSearch$ctl01$txtSearchValue' and @type = 'text' and @id = 'uclCust_uclCust_umd_ctl00_ucS_rptFixedSearch_txtSearchValue_0']</value>
      <webElementGuid>4d8303ce-64fb-42a2-aeb6-1ca09df6d100</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
