<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_mothername</name>
   <tag></tag>
   <elementGuidId>d89de7e5-5827-491a-aba1-3efa26500c40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtMthrMaidenName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtMthrMaidenName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d60174f-5427-425b-88c7-257b7df63140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtMthrMaidenName</value>
      <webElementGuid>f8af5f63-7e85-4bf0-8c84-71e466452de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93bb0d4b-21f0-41f1-a350-a7c779b34f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>HO JAN LING</value>
      <webElementGuid>ec6a2397-2e32-4ea3-8895-90b2bf0b2d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMthrMaidenName</value>
      <webElementGuid>1e6081aa-89d3-4e01-8dbe-3686701196d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>c5fbce9a-32ff-4c2a-8e49-7191d82f0123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled txtLongInputStyle</value>
      <webElementGuid>fb2dbac3-6c9c-47ed-840a-4bec127c9362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMthrMaidenName&quot;)</value>
      <webElementGuid>99533f87-6ecd-4631-9cea-81f7ba3355e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>73abe8bd-881b-499e-b4fb-a866312fac49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtMthrMaidenName']</value>
      <webElementGuid>e2a36a69-24b9-4be3-b670-17c683c61c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tableCust']/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>46d5f03f-c258-4916-8d50-26e3c8a6df38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>86957936-dcbb-426d-ae45-3b4aaa156059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtMthrMaidenName' and @type = 'text' and @id = 'txtMthrMaidenName']</value>
      <webElementGuid>d20f11dc-2e8b-45a8-8895-d2db16e40a9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
