<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_idno</name>
   <tag></tag>
   <elementGuidId>cdd22a14-02bc-46e7-ac9c-7ec54e3234a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ucIdCust_txtCustIdNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ucIdCust_txtCustIdNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>544efb5e-6316-4868-8208-2e1a56f5c2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ucIdCust$txtCustIdNo</value>
      <webElementGuid>d3c5cea1-d720-4018-8391-f6ba763b1b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8bdfa985-2e2d-4451-896c-681b2b7448d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3173042711880007</value>
      <webElementGuid>470a3dee-6e91-4722-8542-00feec4e11af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e3bd4d9d-7c6a-41a7-8a21-06a54045ce48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ucIdCust_txtCustIdNo</value>
      <webElementGuid>01a77992-54b3-457b-9fd8-be57cd9b3bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>cf143d51-18a2-42a9-8cd2-03145980dd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspNetDisabled txtMedInputStyle</value>
      <webElementGuid>bb01269c-c321-4cb8-88ee-4f20881536fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ucIdCust_txtCustIdNo&quot;)</value>
      <webElementGuid>bace0070-1f15-46ec-a8d3-04cfc95e9765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>5fc024a1-eb7c-4c45-9084-075c102b7762</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ucIdCust_txtCustIdNo']</value>
      <webElementGuid>be6db2f3-a010-4a75-909b-cf2be8fbb0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='infoID']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>1fc65e7a-0aa2-4ed1-b6b7-5925088b4251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>38b55879-3d54-4f5b-ad27-2d0af2f1f895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ucIdCust$txtCustIdNo' and @type = 'text' and @id = 'ucIdCust_txtCustIdNo']</value>
      <webElementGuid>6e76ae6b-32d8-4953-a7e9-1374e5e2b729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
