<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_company</name>
   <tag></tag>
   <elementGuidId>874f717b-fa24-4bfa-b1f9-e0067bfd0704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rblCustType_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rblCustType_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a555793-d641-41ad-b3c2-dfa73220354c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rblCustType_1</value>
      <webElementGuid>e30f8e8e-f9cd-47cc-8081-92c8f3a0b7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1ec8f17d-9779-434a-8e88-8cef45e97001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rblCustType</value>
      <webElementGuid>03a04933-6476-49fa-89d0-9a5274f1825b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>37078dd2-a117-4abd-81ca-b38a9ad814d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'rblCustType$1\',\'\')', 0)</value>
      <webElementGuid>46613866-2dcb-4cb3-91ba-715e343fa0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rblCustType_1&quot;)</value>
      <webElementGuid>1c278471-1794-4fa7-a0e3-bfe2b695bf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>e35a2fbe-789a-48cc-98c3-2b77ff351b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rblCustType_1']</value>
      <webElementGuid>28149e19-4407-419d-9af1-deeef30ead1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rblCustType']/tbody/tr/td[2]/input</value>
      <webElementGuid>134de425-9324-47aa-bfa5-9bd23fa0d5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>a1c4f5f9-08ff-4b94-86c6-54105425c03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rblCustType_1' and @type = 'radio' and @name = 'rblCustType']</value>
      <webElementGuid>1095089b-daf5-4347-8ef1-f7e7984523c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
