<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_custname</name>
   <tag></tag>
   <elementGuidId>5e2860a6-6cf1-4166-be5f-ba803c61652b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uclCust_uclCust_imb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uclCust_uclCust_imb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25157335-f0b2-4b32-b7e3-1076e7fdabc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>29ff3d9c-69b1-4358-879d-2ae1dfbc41de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uclCust$uclCust$imb</value>
      <webElementGuid>d7db9faf-426e-49fe-9069-b0dec67c9295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uclCust_uclCust_imb</value>
      <webElementGuid>2e017bbe-bc76-435d-b9b9-9e9cee19f32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../Images/Icon/IconLookup.gif</value>
      <webElementGuid>f16863b7-3e57-4e1c-93e5-b84e5481c820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>overlay('mdnuclCust_uclCust');</value>
      <webElementGuid>a2b38021-40ed-46b8-af69-32bb75d706b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uclCust_uclCust_imb&quot;)</value>
      <webElementGuid>49f783d4-cbde-4cc6-8eea-87cf7859a3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/NAP_Customer/iframe_Term  Condition_appForm</value>
      <webElementGuid>28984db0-9502-4533-b836-b5984f744bb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uclCust_uclCust_imb']</value>
      <webElementGuid>23b935da-67b0-47cd-8650-e131d79f3452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='trUclCust']/td[2]/ul/li/input[2]</value>
      <webElementGuid>76080dd4-2211-439b-96b6-847d3fc4880a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input[2]</value>
      <webElementGuid>888924b9-42a5-4edc-a024-8a287e729f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'uclCust$uclCust$imb' and @id = 'uclCust_uclCust_imb' and @src = '../../../../Images/Icon/IconLookup.gif']</value>
      <webElementGuid>8264206a-d0e6-44d2-ac1d-bebf90202b70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
