<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_login</name>
   <tag></tag>
   <elementGuidId>2a39cb97-0e6c-4e6f-a799-76a889b2aa2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lbLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lbLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88b6d249-ab98-4cad-9792-71975a6ccbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>877caaf4-5f6d-4533-95fe-f71b4f1c12c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lbLogin</value>
      <webElementGuid>0c105359-3145-4e6f-b340-3c691fe6bd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>3b62ebd8-2ad9-4744-b8ac-241dfbc17218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>triggerLoginClick();__doPostBack('lbLogin','')</value>
      <webElementGuid>7280d691-6f26-49fb-b819-f67dff0e80c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lbLogin</value>
      <webElementGuid>35225c06-3fa1-494e-80d6-9aa04525c2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lbLogin&quot;)</value>
      <webElementGuid>b9e86ba3-623b-4b3c-a9fe-02ebc0405f89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lbLogin']</value>
      <webElementGuid>7665d1ea-e924-4622-83de-b5e7da6a240f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upButton']/div/input</value>
      <webElementGuid>d1177d52-6e73-47b5-b7ce-e016aa1f747d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>7b9fb679-1694-4061-b8e2-b283c91d287c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'lbLogin' and @id = 'lbLogin']</value>
      <webElementGuid>0d565970-f2d7-4a02-bdff-2c1d2d42c38d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
